version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5454:5454"
    depends_on: 
      - database
  frontend:
    build: ./frontend
    ports:
      - 8080:80
    depends_on:
     - backend
  database:
    image: mongo
    restart: always

